# Generated by Django 4.2 on 2024-08-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_room_user1_room_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
    ]
